=== AdairPonceuwu/WS_7-proyects-XML-DTD-XML-SCHEMA-/Email/Email_Val.dtd
<!ELEMENT root (email+)>
<!ATTLIST root xmlns:xsi CDATA #REQUIRED>
<!ATTLIST root xsi:noNamespaceSchemaLocation CDATA #REQUIRED>
<!ELEMENT email (head, body)>
<!ATTLIST email num  CDATA #REQUIRED>
<!ELEMENT head (from, to, subject)>
<!ELEMENT from (name, adress)>
<!ELEMENT to (name, adress)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT body (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT adress (#PCDATA)>

=== AdairPonceuwu/WS_7-proyects-XML-DTD-XML-SCHEMA-/Email/Email.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE root SYSTEM "Email_Val.dtd">

<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Email_Schema.xsd">

    <email num="1">
        <head>

            <from>
                <name>Adair Ponce</name>
                <adress>adair.ponce@alumno.buap.mx</adress>
            </from>

            <to>
                <name>An Flores</name>
                <adress>an@gmail.com</adress>
            </to>

            <subject>
                I miss you
            </subject>

        </head>

        <body>
            Come back to me please
        </body>

    </email>

    <email num="2">
        <head>

            <from>
                <name>Adair Ponce</name>
                <adress>adair.ponce@alumno.buap.mx</adress>
            </from>

            <to>
                <name>Estefani Ramirez</name>
                <adress>es@gmail.com</adress>
            </to>

            <subject>
                I miss you too
            </subject>

        </head>

        <body>
            Come back to me please, ily
        </body>

    </email>

    <email num="3">
        <head>

            <from>
                <name>Adair Ponce</name>
                <adress>adair.ponce@alumno.buap.mx</adress>
            </from>

            <to>
                <name>Diana Hernandez</name>
                <adress>diana@gmail.com</adress>
            </to>

            <subject>
                I miss you more than ever
            </subject>

        </head>

        <body>
            Ily 
        </body>

    </email>
</root>
