=== AdairPonceuwu/WS_7-proyects-XML-DTD-XML-SCHEMA-/CV/CV_Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Definición del elemento principal "cv" -->
    <xs:element name="cv">
        <xs:complexType>
            <xs:sequence>
                <!--"datos_personales" -->
                <xs:element name="datos_personales">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre_completo" type="xs:string"/>
                            <xs:element name="direccion" type="xs:string"/>
                            <xs:element name="telefono" type="xs:string"/>
                            <xs:element name="email" type="xs:string"/>
                            <xs:element name="fecha_nacimiento" type="xs:string"/>
                            <xs:element name="descripcion" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!--"educacion" -->
                <xs:element name="educacion">
                    <xs:complexType>
                        <xs:sequence>
                            <!--"datos_preparatoria"-->
                            <xs:element name="datos_preparatoria">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre_escuela" type="xs:string"/>
                                        <xs:element name="generacion" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <!--"datos_universidad"-->
                            <xs:element name="datos_universidad">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre_escuela" type="xs:string"/>
                                        <xs:element name="carrera" type="xs:string"/>
                                        <xs:element name="matricula" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!--"experiencia_laboral"-->
                <xs:element name="experiencia_laboral">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre_empresa" type="xs:string"/>
                            <xs:element name="lugar" type="xs:string"/>
                            <xs:element name="cargo" type="xs:string"/>
                            <xs:element name="actividades_realizadas" type="xs:string"/>
                            <xs:element name="periodo" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- Definición del elemento skills -->
                <xs:element name="skills">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="tec" minOccurs="1" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:sequence>
                            <xs:element name="nombre_tec" type="xs:string"/>
                            <xs:element name="nivel_tec" type="xs:string"/>
                            </xs:sequence>
                            <xs:attribute name="num" type="xs:integer" use="required"/>
                        </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- Definición del elemento idioma -->
                <xs:element name="idioma">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="idiom" minOccurs="1" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:sequence>
                            <xs:element name="nombre_idioma" type="xs:string"/>
                            <xs:element name="nivel_idioma" type="xs:string"/>
                            </xs:sequence>
                            <xs:attribute name="num" type="xs:integer" use="required"/>
                        </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType> 
    </xs:element>
</xs:schema>

=== AdairPonceuwu/WS_7-proyects-XML-DTD-XML-SCHEMA-/CV/CV_Est.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "CV_Val.dtd">

<cv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CV_Schema.xsd">

    <datos_personales>
        <nombre_completo>Adair Ponce Luna</nombre_completo>
        <direccion>2DA Privada de la Noria</direccion>
        <telefono>2226129277</telefono>
        <email>adair.ponce@alumno.buap.mx</email>
        <fecha_nacimiento>21/08/02</fecha_nacimiento>
        <descripcion>Me consiedero un profesional responsable y dedicado, con habilidades demostradas 
        en la gestión eficaz de tareas y actividades. Perseverante y tolerante, abordo 
        desafíos con calma y adaptabilidad. Siempre listo para nuevas experiencias, 
        me destaco por aprender rápidamente y contribuir de manera positiva en entornos 
        laborales.</descripcion>
    </datos_personales>

    <educacion>
        <datos_preparatoria>
            <nombre_escuela>CONALEP Puebla III</nombre_escuela>
            <generacion>2017-2020</generacion>
        </datos_preparatoria>

        <datos_universidad>
            <nombre_escuela>BUAP</nombre_escuela>
            <carrera>Lic. en Ing. en Ciencias de la Computacion</carrera>
            <matricula>202051992</matricula>
        </datos_universidad>
    </educacion>

    <experiencia_laboral>
        <nombre_empresa></nombre_empresa>
        <lugar></lugar>
        <cargo></cargo>
        <actividades_realizadas></actividades_realizadas>
        <periodo></periodo> 
    </experiencia_laboral>

    <skills>
        <tec num="1">
            <nombre_tec>Python3</nombre_tec>
            <nivel_tec>Intermedio</nivel_tec>
        </tec>

        <tec num="2">
            <nombre_tec>SQL</nombre_tec>
            <nivel_tec>Intermedio</nivel_tec>
        </tec>
    </skills>

    <idioma>
        <idiom num="1">
            <nombre_idioma>Español</nombre_idioma>
            <nivel_idioma>Nativo</nivel_idioma>
        </idiom>

        <idiom num="2">
            <nombre_idioma>Inglés</nombre_idioma>
            <nivel_idioma>B2</nivel_idioma>
        </idiom>


    </idioma>

</cv>
