=== AdairPonceuwu/WS_7-proyects-XML-DTD-XML-SCHEMA-/Arbol Genealogico/familia_val.dtd
<!ELEMENT arbol_genealogico (familia+)>
<!ATTLIST arbol_genealogico xmlns:xsi CDATA #REQUIRED>
<!ATTLIST arbol_genealogico xsi:noNamespaceSchemaLocation CDATA #REQUIRED>
<!ELEMENT familia (familiar+)>
<!ELEMENT familiar (familiar*)>
<!ATTLIST familiar
    nombre CDATA #REQUIRED
    relacion_mia CDATA #IMPLIED
>

=== AdairPonceuwu/WS_7-proyects-XML-DTD-XML-SCHEMA-/Arbol Genealogico/familia.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE arbol_genealogico SYSTEM "familia_val.dtd">
<arbol_genealogico >
    <familia>
        <familiar nombre="Ismael Ponce" relacion_mia="Abuelo">
            <familiar nombre="Ismael Ponce" relacion_mia="Padre">
                <familiar nombre="Adair Ponce" relacion_mia="Hijo"/>
                <familiar nombre="Tzuriel Ponce" relacion_mia="Hermano"/>
            </familiar>
            <familiar nombre="Gustavo Ponce" relacion_mia="Tío"/>
        </familiar>
        <familiar nombre="Amalia Vivar" relacion_mia="Abuela">
            <familiar nombre="Ismael Ponce" relacion_mia="Padre"/>
            <familiar nombre="Gustavo Ponce" relacion_mia="Tío"/>
        </familiar>
        <familiar nombre="Alfonso Luna" relacion_mia="Abuelo">
            <familiar nombre="Elena Luna" relacion_mia="Madre">
                <familiar nombre="Adair Ponce" relacion_mia="Hijo"/>
                <familiar nombre="Tzuriel Ponce" relacion_mia="Hermano"/>
            </familiar>
            <familiar nombre="Araceli Luna" relacion_mia="Tía"/>
            <familiar nombre="Alfonso Luna" relacion_mia="Tío"/>
        </familiar>
        <familiar nombre="Emilia Luna">
            <familiar nombre="Elena Luna" relacion_mia="Madre"/>
            <familiar nombre="Araceli Luna" relacion_mia="Tía"/>
            <familiar nombre="Alfonso Luna" relacion_mia="Tío"/>
        </familiar>
    </familia>
</arbol_genealogico>
