=== AdairPonceuwu/WS_7-proyects-XML-DTD-XML-SCHEMA-/Biblioteca/biblioteca_val.dtd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!ELEMENT biblioteca (libro+)>
<!ELEMENT libro (autor, capitulo+)>
<!ATTLIST libro ISBN CDATA #REQUIRED>
<!ELEMENT autor (nombre, email, direccion)>
<!ELEMENT capítulo (seccion+)>
<!ATTLIST capítulo nombre CDATA #REQUIRED>
<!ELEMENT seccion (titulo*, nombre*, contenido*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT título (#PCDATA)>
<!ELEMENT contenido (#PCDATA)>

=== AdairPonceuwu/WS_7-proyects-XML-DTD-XML-SCHEMA-/Biblioteca/biblioteca.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca_val.dtd">

<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:NamespaceSchemaLocations="biblioteca_schema.xsd">

  <libro ISBN="0-596-00292-0">

        <autor>
            <nombre>Adair Ponce</nombre>
            <email>nosequien@oreilly.com/ail</email>
            <direccion>Avenida del Conocimiento </direccion>
        </autor>

        <capitulo nombre="Bienvenida">
            <seccion>
                <titulo>Introduccion a los compiladores</titulo>
            </seccion>

            <seccion>
                <nombre>¿Qué es un compilador?</nombre>
                <contenido>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore ma</contenido>
            </seccion>

        </capitulo>
  </libro>

  <libro ISBN="0-596-00292-0">

        <autor>
            <nombre>Elliotte Rusty Harold, W. Scott Means</nombre>
            <email>elliottscott@oreilly.com/ail</email>
            <direccion>1005 Gravenstein Highway North, CA 3472 </direccion>
        </autor>

        <capitulo nombre="Introduccion">
            <seccion>
                <titulo>XML Conceps</titulo>
            </seccion>

            <seccion>
                <nombre>Introducing XML</nombre>
                <contenido>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore ma</contenido>
            </seccion>

        </capitulo>
  </libro>

  <libro ISBN="0-596-00292-0">

        <autor>
            <nombre>Ana Perez</nombre>
            <email>anperez@oreilly.com/ail</email>
            <direccion>Avenida de las matematicas</direccion>
        </autor>

        <capitulo nombre="Prologo">
            <seccion>
                <titulo>Geofisica para novatos</titulo>
            </seccion>

            <seccion>
                <nombre>Geofisica</nombre>
                <contenido>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore ma</contenido>
            </seccion>

        </capitulo>
  </libro>

</biblioteca>
