=== AdairPonceuwu/WS_7-proyects-XML-DTD-XML-SCHEMA-/Cartelera/Cartelera_Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- "cine" -->
  <xs:element name="cine">
    <xs:complexType>
      <xs:sequence>
        <!-- "cinemex" -->
        <xs:element name="cinemex" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <!-- "pelicula" -->
              <xs:element name="pelicula" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="clasificacion" type="xs:string"/>
                            <xs:element name="duracion" type="xs:string"/>
                            <xs:element name="genero" type="xs:string"/>
                            <xs:element name="idioma" type="xs:string"/>
                            <xs:element name="horarios" type="xs:string"/>
                            <xs:element name="director" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="num" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
              </xs:sequence>
          </xs:complexType>
        </xs:element>
        <!-- "cinepolis" -->
        <xs:element name="cinepolis" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <!-- "pelicula" -->
                 <xs:element name="pelicula" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="clasificacion" type="xs:string"/>
                            <xs:element name="duracion" type="xs:string"/>
                            <xs:element name="genero" type="xs:string"/>
                            <xs:element name="idioma" type="xs:string"/>
                            <xs:element name="horarios" type="xs:string"/>
                            <xs:element name="director" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="num" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AdairPonceuwu/WS_7-proyects-XML-DTD-XML-SCHEMA-/Cartelera/Cartelera.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE cine SYSTEM "Cartelera_Val.dtd">

<cine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Cartelera_Schema.xsd">

    <cinemex>
        <pelicula num="1">
            <titulo>About time</titulo>
            <clasificacion>B</clasificacion>
            <duracion>123 min</duracion>
            <genero>Romance</genero>
            <idioma>Español</idioma>
            <horarios> 01:30 p.m. 03:40 p.m. 05:50 p.m. 08:00 p.m. 10:05 p.m. </horarios>
            <director>Richard Curtis</director>
        </pelicula>

        <pelicula num="2">
            <titulo>About time</titulo>
            <clasificacion>B</clasificacion>
            <duracion>123 min</duracion>
            <genero>Romance</genero>
            <idioma>Español</idioma>
            <horarios> 01:30 p.m. 03:40 p.m. 05:50 p.m. 08:00 p.m. 10:05 p.m. </horarios>
            <director>Richard Curtis</director>
        </pelicula>

        <pelicula num="3">
            <titulo>About time</titulo>
            <clasificacion>B</clasificacion>
            <duracion>123 min</duracion>
            <genero>Romance</genero>
            <idioma>Español</idioma>
            <horarios> 01:30 p.m. 03:40 p.m. 05:50 p.m. 08:00 p.m. 10:05 p.m. </horarios>
            <director>Richard Curtis</director>
        </pelicula>

    </cinemex>

    <cinepolis>
        <pelicula num="1">
            <titulo>About time</titulo>
            <clasificacion>B</clasificacion>
            <duracion>123 min</duracion>
            <genero>Romance</genero>
            <idioma>Español</idioma>
            <horarios> 01:30 p.m. 03:40 p.m. 05:50 p.m. 08:00 p.m. 10:05 p.m. </horarios>
            <director>Richard Curtis</director>
        </pelicula>

        <pelicula num="2">
            <titulo>About time</titulo>
            <clasificacion>B</clasificacion>
            <duracion>123 min</duracion>
            <genero>Romance</genero>
            <idioma>Español</idioma>
            <horarios> 01:30 p.m. 03:40 p.m. 05:50 p.m. 08:00 p.m. 10:05 p.m. </horarios>
            <director>Richard Curtis</director>
        </pelicula>

        <pelicula num="3">
            <titulo>About time</titulo>
            <clasificacion>B</clasificacion>
            <duracion>123 min</duracion>
            <genero>Romance</genero>
            <idioma>Español</idioma>
            <horarios> 01:30 p.m. 03:40 p.m. 05:50 p.m. 08:00 p.m. 10:05 p.m. </horarios>
            <director>Richard Curtis</director>
        </pelicula>

    </cinepolis>


</cine>
