=== AdairPonceuwu/WS_7-proyects-XML-DTD-XML-SCHEMA-/Canciones/Canciones_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           targetNamespace="http://www.example.com/redtube"
           elementFormDefault="qualified">

    <!--"redtube" -->
    <xs:element name="redtube">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="playlist"/>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cancion"  maxOccurs="unbounded"/>
                                <xs:complexType name="CancionType">
                                        <xs:sequence>
                                            <xs:element name="titulo" type="xs:string"/>
                                            <xs:element name="cantante" type="xs:string"/>
                                            <xs:element name="duracion" type="xs:string"/>
                                            <xs:element name="genero" type="xs:string"/>
                                            <xs:element name="album" type="xs:string"/>
                                            <xs:element name="anio" type="xs:string"/>
                                        </xs:sequence>
                                        <xs:attribute name="num" type="xs:string" use="required"//>
                                 </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="nombre" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AdairPonceuwu/WS_7-proyects-XML-DTD-XML-SCHEMA-/Canciones/Canciones.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE redtube SYSTEM "Canciones_val.dtd">   

<redtube xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Canciones_schema.xsd">

    <playlist nombre="Gean">

        <cancion num="1">
            <titulo>Siempre tuyo</titulo>
            <cantante>Tranzas</cantante>
            <duracion>4:00 min.</duracion>
            <genero>Pop</genero>
            <album>Tranzas por siempre</album>
            <anio>2003</anio>
        </cancion>

        <cancion num="2">
            <titulo>Dos mundos</titulo>
            <cantante>Enjambre</cantante>
            <duracion>3:59 min.</duracion>
            <genero>Pop rock</genero>
            <album>IDK</album>
            <anio>2009</anio>
        </cancion>

        <cancion num="3">
            <titulo>Se√±ales Luminosas</titulo>
            <cantante>Gustavo Cerati</cantante>
            <duracion>3:59 min.</duracion>
            <genero>Pop rock</genero>
            <album>Siempre Es Hoy</album>
            <anio>2002</anio>
        </cancion>

    </playlist>

</redtube>
