=== AdairPonceuwu/WS_7-proyects-XML-DTD-XML-SCHEMA-/Receta/Receta_Val.dtd
<!ELEMENT receta (nombre, descripcion, ingredientes, instrucciones)>
<!ATTLIST receta xmlns:xsi CDATA #REQUIRED>
<!ATTLIST receta xsi:noNamespaceSchemaLocation CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT ingredientes (ingrediente+)>
<!ELEMENT ingrediente (item, cantidad)>
<!ELEMENT item (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ATTLIST cantidad unidad CDATA #REQUIRED>
<!ELEMENT instrucciones (paso+)>
<!ELEMENT paso (#PCDATA)>
<!ATTLIST paso num CDATA #REQUIRED>

=== AdairPonceuwu/WS_7-proyects-XML-DTD-XML-SCHEMA-/Receta/Receta.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE receta SYSTEM "Receta_Val.dtd">

<receta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:NamespaceSchemaLocation="Receta_Schema.xsd">
    
    <nombre>
        Licuado de Platano
    </nombre>

    <descripcion>
        Un licuado para un buen desayuno antes de la universidad.
    </descripcion>

    <ingredientes>

        <ingrediente>

            <itema>Platano</itema>
            <cantidad unidad="1 pza"/>

        </ingrediente>

        <ingrediente>
            <itema>Leche</itema>
            <cantidad unidad="1 cup"/>
        </ingrediente>

        <ingrediente>
            <itema>Escencia de vainilla</itema>
            <cantidad unidad="1/2 cucharada"/>
        </ingrediente>

    </ingredientes>

    <instrucciones>
        <paso num="1">
            Ponga el platano pelado y la leche en la licuadora.
        </paso>

        <paso num="2">
            Agregue la cucharada de escencia de vainilla y licue todo.
        </paso>

        <paso num="3">
            Sirva en su vaso favorito.
        </paso>

    </instrucciones>

</receta>
